// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/spf13/cobra"
	"github.com/xuender/fairy/meta"
	"github.com/xuender/fairy/move"
	"github.com/xuender/fairy/pb"
	"github.com/xuender/fairy/ui"
)

// Injectors from wire.go:

func InitMeta(cmd *cobra.Command) *meta.Service {
	service := meta.NewService()
	return service
}

func InitUI(cmd *cobra.Command) *ui.Service {
	config := pb.NewConfig(cmd)
	service := ui.NewService(config)
	return service
}

func InitMove(cmd *cobra.Command) *move.Service {
	config := pb.NewConfig(cmd)
	service := meta.NewService()
	moveService := move.NewService(config, service)
	return moveService
}

func InitGUI(cmd *cobra.Command) *ui.UI {
	config := pb.NewConfig(cmd)
	uiUI := ui.NewUI(config)
	return uiUI
}
