// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/spf13/cobra"
	"github.com/xuender/fairy/meta"
	"github.com/xuender/fairy/pb"
	"github.com/xuender/fairy/ui"
	"github.com/xuender/fairy/watch"
)

// Injectors from wire.go:

func InitMeta(cmd *cobra.Command) *meta.Service {
	service := meta.NewService()
	return service
}

func InitUI(cmd *cobra.Command) *ui.Service {
	config := pb.NewConfig(cmd)
	service := ui.NewService(config)
	return service
}

func InitWatch(cmd *cobra.Command) *watch.Service {
	config := pb.NewConfig(cmd)
	service := meta.NewService()
	watchService := watch.NewService(config, service)
	return watchService
}
